version: "3"

services: 
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres_data/:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:7.0
    container_name: pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: username@hostname.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin
